Adds support for splitting properties, and many other changes. - Fixes how certain properties are checked. - It is now possible to check each property separately. - Updates regression tests. - Many other changes related to properties.

diff --git a/regression-tests/horn-contracts/runtests b/regression-tests/horn-contracts/runtests
--- a/regression-tests/horn-contracts/runtests
+++ b/regression-tests/horn-contracts/runtests
@@ -14,6 +14,6 @@ TESTS="contract1.hcc \
 for name in $TESTS; do
     echo
     echo $name
-    $LAZABS -cex -acsl "$@" $name 2>&1 | grep -v 'at '
+    { $LAZABS -cex -acsl "$@" $name > >(tee stdout.log) 2> >(grep ' Error' >&2); }
 done
 
